version: '3'
# networks:
  # server:
  #   name: server
  #   driver: bridge
  #   external: true
services:
  server:
    container_name: server
    build: server
    image: server:latest
    restart: unless-stopped
    # volumes:
    #   - ./server/config:/opt/app/config
    #   - ./server/src:/opt/app/src
    #   - ./server/package.json:/opt/package.json
    #   - ./server/package-lock.json:/opt/package-lock.json
    #   - ./server/.env:/opt/app/.env
    #   - ./server/public/uploads:/opt/app/public/uploads
    ports:
      - '3000:3000'
    # networks:
    #   - server
  front:
    container_name: front
    image: front:latest
    build: front
    ports:
      - "8000:8000"
    # networks:
    #   - server
  dashboard:
    container_name: dashboard
    image: dashboard:latest
    build: dashboard
    ports:
      - "8080:8080"
    # networks:
    #   - server